src/backend/corefac/urls.py
from django.urls import path
from corefac import views


app_name = 'corefac'
urlpatterns = [
    path('', views.corefac_home, name='home'),
    path('sampleprep/method/add/', views.add_sampleprep_method),
    path('sampleprep/version/add/', views.add_sampleprep_method_version),
    path('sampleprep/method/edit/', views.edit_sampleprep_method),
    path('sampleprep/version/edit/', views.edit_sampleprep_method_version),
    path('sampleprep/method/disable/', views.disable_sampleprep_method),

    path('sampleprep/version/disable/', views.disable_sampleprep_method_version),
    path('sampleprep/method/enable/', views.enable_sampleprep_method),
    path('sampleprep/version/enable/', views.enable_sampleprep_method_version),
    path('sampleprep/method/delete/', views.delete_sampleprep_method),
    path('sampleprep/version/delete/', views.delete_sampleprep_method_version),

    path('sampleprep/pipeline/add/', views.add_sampleprep_pipeline),
    path('sampleprep/pipeline/edit/', views.edit_sampleprep_pipeline),
    path('sampleprep/pipeline/lock/', views.lock_sampleprep_pipeline),
    path('sampleprep/pipeline/disable/', views.disable_sampleprep_pipeline),
    path('sampleprep/pipeline/enable/', views.enable_sampleprep_pipeline),
    path('sampleprep/pipeline/delete/', views.delete_sampleprep_pipeline),
]

src/backend/dashboard/urls.py
from django.urls import path
from dashboard import views


app_name = 'dashboard'
urlpatterns = [
    path('', views.dashboard, name='dash'),
    path('longqc/<int:instrument_id>/<int:daysago>/<int:maxdays>', views.show_qc, name='longqc'),
    path('proddata/<int:daysago>/<int:maxdays>', views.get_file_production),
]

src/backend/datasets/urls.py
from django.urls import path
from datasets import views

app_name = 'datasets'
urlpatterns = [
    path('new/', views.new_dataset, name="new"),
    path('show/<int:dataset_id>/', views.show_dataset, name="show"),
    path('show/info/<int:dataset_id>/', views.dataset_info),
    path('show/info/', views.dataset_info),
    path('show/project/<int:project_id>/', views.get_project),
    path('show/files/<int:dataset_id>/', views.dataset_files, name="showfiles"),
    path('show/files/', views.dataset_files),
    path('find/files/', views.find_files),
    path('show/samples/<int:dataset_id>/', views.dataset_samples),
    path('show/samples/', views.dataset_samples),
    path('show/labelcheck/<int:dataset_id>/', views.labelcheck_samples),
    path('show/labelcheck/', views.labelcheck_samples),
    path('show/msacq/<int:dataset_id>/', views.dataset_msacq),
    path('show/msacq/', views.dataset_msacq),
    path('show/mssampleprep/<int:dataset_id>/', views.dataset_mssampleprep),
    path('show/mssampleprep/', views.dataset_mssampleprep),
    path('show/components/<int:datatype_id>/', views.get_datatype_components),
    path('show/species/', views.get_species),
    path('save/dataset/', views.save_dataset, name="savedset"),
    path('save/dataset/lock/', views.lock_dataset), 
    path('save/dataset/unlock/', views.unlock_dataset), 
    path('save/files/', views.save_files, name="savefiles"),
    path('save/files/pending/', views.accept_or_reject_dset_preassoc_files),
    path('save/mssampleprep/', views.save_ms_sampleprep),
    path('save/mssampleprep/tracking/', views.save_ms_sampleprep_tracking_step),
    path('save/msacq/', views.save_ms_acquisition),
    path('save/samples/', views.save_samples),
    path('save/labelcheck/', views.save_labelcheck),
    path('save/owner/', views.change_owners, name="changeowner"),
    path('rename/project/', views.rename_project),
    path('merge/projects/', views.merge_projects),
    path('archive/dataset/', views.move_dataset_cold),
    path('archive/project/', views.move_project_cold),
    path('undelete/dataset/', views.move_dataset_active),
    path('undelete/project/', views.move_project_active),
    path('purge/project/', views.purge_project),
    path('purge/dataset/', views.purge_dataset),
]

src/backend/home/urls.py
from django.urls import path
from home import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name="home"),
    path('show/datasets/', views.show_datasets, name="showdatasets"),
    path('show/projects/', views.show_projects, name="showprojects"),
    path('show/analyses/', views.show_analyses, name="showanalyses"),
    path('show/jobs/', views.show_jobs, name="showjobs"),
    path('show/files/', views.show_files, name="showfiles"),
    path('find/datasets/', views.find_datasets, name="finddatasets"),
    path('find/projects/', views.find_projects, name="findprojects"),
    path('find/analyses/', views.find_analysis, name="findanalyses"),
    path('find/files/', views.find_files, name="findfiles"),
    path('show/dataset/<int:dataset_id>', views.get_dset_info, name="dsinfo"),
    path('show/project/<int:proj_id>', views.get_proj_info, name="projinfo"),
    path('show/file/<int:file_id>', views.get_file_info, name="fninfo"),
    path('show/analysis/<int:anid>', views.get_analysis_info, name="anainfo"),
    path('show/job/<int:job_id>', views.get_job_info, name="jobinfo"),
    path('messages/', views.show_messages, name="messages"),
    path('refresh/job/<int:job_id>', views.refresh_job, name="jobrefresh"),
    path('refresh/analysis/<int:anid>', views.refresh_analysis, name="analysisrefresh"),
    path('createmzml/', views.create_mzmls),
    path('refinemzml/', views.refine_mzmls),
]

src/backend/kantele/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manage/', include('staffpage.urls')),
    path('files/', include('rawstatus.urls')),
    path('datasets/', include('datasets.urls')),
    path('jobs/', include('jobs.urls')),
    path('dash/', include('dashboard.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('home.urls')),
    path('analysis/', include('analysis.urls')),
    path('mstulos/', include('mstulos.urls')),
    path('corefac/', include('corefac.urls')),
]

src/backend/mstulos/urls.py
from django.urls import path
from mstulos import views

app_name = 'mstulos'
urlpatterns = [
        path('', views.frontpage, name='front'),
        path('upload/init/', views.init_store_experiment, name='init_store'),
        path('add/<int:ana_id>/', views.add_analysis),
        path('peptides/', views.peptide_table),
        path('psms/', views.psm_table),
        path('upload/proteins/', views.upload_proteins, name='upload_proteins'),
        path('upload/peptides/', views.upload_peptides, name='upload_peptides'),
        path('upload/psms/', views.upload_psms, name='upload_psms'),
        path('upload/genes/', views.upload_genes, name='upload_geneq'),
        path('upload/done/', views.upload_done, name='upload_done'),
        path('plotdata/peptides/', views.fetch_plotdata_peptides),
        path('plotdata/psms/', views.fetch_plotdata_psms),
        path('plotdata/genes/', views.fetch_plotdata_genes),
        ]

src/backend/templates/base.html
<html>
<head>
	<meta charset='utf-8'>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Kantele - metadata management</title>

  {% block head %}
  {% endblock head %}

  {% load static %}
  {{ user.is_staff|json_script:'admin'}}
  <script>
    is_staff = JSON.parse(document.getElementById('admin').text);
  </script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  <link rel="stylesheet" type="text/css" href="{% static "datasets/style.css" %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>

<body>
	<nav id="navMenu" class="navbar is-light">
	  <div class="navbar-brand">
	  	<a class="navbar-item" href="{% url 'home:home' %}"><img id="navMenuLogo" src="{% static "datasets/logo.svg" %}"></a>
	  </div>
	  {% if user.is_authenticated %}
	  <div class="navbar-menu">
	    <div class="navbar-start">
		  {% with request.resolver_match.app_name as appname %}
		  <a class="navbar-item {% if appname == 'home' %}is-active{% endif %}" href="{% url 'home:home' %}">HOME</a>
		    <a class="navbar-item {% if appname == 'datasets' %}is-active{% endif %}" href="{% url 'datasets:new' %}">NEW DATASET</a>
		    <a class="navbar-item {% if appname == 'dashboard' %}is-active{% endif %}" href="{% url 'dashboard:dash' %}">DASHBOARD</a>
		    <a class="navbar-item {% if appname == 'files' %}is-active{% endif %}" href="{% url 'files:inflow' %}">DATA UPLOADS</a>
		    <a class="navbar-item {% if appname == 'mstulos' %}is-active{% endif %}" href="{% url 'mstulos:front' %}">RESULTS VIEWER</a>
	  	    {% if user.is_staff %}
		    <a class="navbar-item {% if appname == 'corefac' %}is-active{% endif %}" href="{% url 'corefac:home' %}">CORE FACILITY</a>
		    <a class="navbar-item {% if appname == 'staffpage' %}is-active{% endif %}" href="{% url 'staffpage:home' %}">ADMIN</a>
		    {% endif %}
		    <a class="navbar-item" href="{% url 'logout' %}">LOGOUT {{ user }}</a>
		  {% endwith %}
	    </div>
    </div>
	{% endif %}
  </nav>

  <div class="container mt-2">
{% block content %}
{% endblock content %}
  </div>

</body>
</html>